### PR TITLE
Maps GetInventory to Easy accesible Object

### PR DESCRIPTION
**Pull request by gallexme**
stores
items,eggs and pokemons into a object

example:
```
var cleanupPokemons= async function (Poke) {
    let inventory = await Poke.GetInventory();
    try {
    for (let pokemon of inventory.pokemons) {
        if (pokemon.cp < 100) {
            console.log("releasing",pokemon.name)
           console.log(await pokemon.release());
           await sleep(2000);
        }
        console.log(pokemon);
    }
    for (let item of inventory.items) {
        //console.log(item);
    }
    } catch(error) {
      //  console.log(error);
    }
    console.log(inventory);
}
```

### CODE REVIEW

**Comment by gallexme** [comment]
Releasing is not working though i always get a 
[i] Received OK: ReleasePokemonResponse
{ ReleasePokemonResponse: { result: 3, candy_awarded: 0 } }

3 means failed

**Comment by gallexme** [comment]
releasing Vulpix
[i] Received OK: ReleasePokemonResponse
{ ReleasePokemonResponse: { result: 3, candy_awarded: 0 } }
Pokemon {
  pokemon_id: 37,
  cp: 10,
  stamina: 10,
  stamina_max: 10,
  move_1: 209,
  move_2: 131,
  deployed_fort_id: 0,
  owner_name: '',
  is_egg: false,
  egg_km_walked_target: 0,
  egg_km_walked_start: 0,
  origin: 0,
  height_m: 0.6230424046516418,
  weight_kg: 10.259743690490723,
  individual_attack: 10,
  individual_defense: 7,
  individual_stamina: 2,
  cp_multiplier: 0.09399999678134918,
  pokeball: 1,
  captured_cell_id: Long { low: 0, high: 1201256704, unsigned: true },
  battles_attacked: 0,
  battles_defended: 0,
  egg_incubator_id: '',
  creation_time_ms: Long { low: 499975783, high: 342, unsigned: true },
  num_upgrades: 0,
  additional_cp_multiplier: 0,
  favorite: 0,
  nickname: '',
  from_fort: 0,
  num: '037',
  name: 'Vulpix',
  img: 'http://www.serebii.net/pokemongo/pokemon/037.png',
  type: 'Fire',
  height: '0.61 m',
  weight: '9.9 kg',
  candy: '50 Vulpix Candy',
  egg: '5 km',
  multipliers: [ 2.74, 2.81 ],
  weaknesses: [ 'Water', 'Ground', 'Rock' ],
  next_evolution: [ { num: '038', name: 'Ninetales' } ],
  catchable: true,
  parent: 
   PokemonGOAPI {
     player: 
      Player {
        parent: [Circular],
        playerInfo: [Object],
        Auth: [Object],
        surroundings: [Object] },
     api: 
      Connection {
        parent: [Circular],
        endPoint: 'https://pgorelease.nianticlabs.com/plfe/208/rpc',
        auth_ticket: [Object] },
     map: PlayerMap {},
     logged: false,
     debug: true,
     useHeartBeat: false } }

**Comment by jimmywarting** [comment]
Can you just show an example of what the result looks like? :)

**Comment by gallexme** [comment]
ah u mean of the GetInventory Function 
sure gonna console.log it and update this comment wait

**Comment by stoffern** [comment]
@gallexme please move the ReleasePokemonResponse into a new issue..

**Comment by gallexme** [comment]
{ pokemons: 
   [ Pokemon {
       pokemon_id: 21,
       cp: 43,
       stamina: 18,
       stamina_max: 18,
       move_1: 219,
       move_2: 80,
       deployed_fort_id: 0,
       owner_name: '',
       is_egg: false,
       egg_km_walked_target: 0,
       egg_km_walked_start: 0,
       origin: 0,
       height_m: 0.24125553667545319,
       weight_kg: 1.1593881845474243,
       individual_attack: 9,
       individual_defense: 5,
       individual_stamina: 5,
       cp_multiplier: 0.21573247015476227,
       pokeball: 1,
       captured_cell_id: [Object],
       battles_attacked: 0,
       battles_defended: 0,
       egg_incubator_id: '',
       creation_time_ms: [Object],
       num_upgrades: 0,
       additional_cp_multiplier: 0,
       favorite: 0,
       nickname: '',
       from_fort: 0,
       num: '021',
       name: 'Spearow',
       img: 'http://www.serebii.net/pokemongo/pokemon/021.png',
       type: 'Normal / Flying',
       height: '0.30 m',
       weight: '2.0 kg',
       candy: '50 Spearow Candy',
       egg: '2 km',
       multipliers: [Object],
       weaknesses: [Object],
       next_evolution: [Object],
       catchable: true,
       parent: [Object] },
     Pokemon {
       pokemon_id: 79,
       cp: 145,
       stamina: 55,
       stamina_max: 55,
       move_1: 230,
       move_2: 105,
       deployed_fort_id: 0,
       owner_name: '',
       is_egg: false,
       egg_km_walked_target: 0,
       egg_km_walked_start: 0,
       origin: 0,
       height_m: 1.1714885234832764,
       weight_kg: 46.40069580078125,
       individual_attack: 5,
       individual_defense: 7,
       individual_stamina: 12,
       cp_multiplier: 0.29024988412857056,
       pokeball: 1,
       captured_cell_id: [Object],
       battles_attacked: 0,
       battles_defended: 0,
       egg_incubator_id: '',
       creation_time_ms: [Object],
       num_upgrades: 0,
       additional_cp_multiplier: 0,
       favorite: 0,
       nickname: '',
       from_fort: 0,
       num: '079',
       name: 'Slowpoke',
       img: 'http://www.serebii.net/pokemongo/pokemon/079.png',
       type: 'Water / Psychic',
       height: '1.19 m',
       weight: '36.0 kg',
       candy: '50 Slowpoke Candy',
       egg: '5 km',
       multipliers: 2.21,
       weaknesses: [Object],
       next_evolution: [Object],
       catchable: true,
       parent: [Object] },
     
     ... 230 more items ],
  items: 
   [ Item { item_id: 901, count: 1, unseen: true, parent: [Object] },
     Item { item_id: 902, count: 2, unseen: false, parent: [Object] },
     Item { item_id: 201, count: 32, unseen: false, parent: [Object] },
     Item { item_id: 701, count: 23, unseen: false, parent: [Object] },
     Item { item_id: 301, count: 2, unseen: false, parent: [Object] },
     Item { item_id: 1, count: 60, unseen: false, parent: [Object] },
     Item { item_id: 2, count: 27, unseen: false, parent: [Object] },
     Item { item_id: 401, count: 5, unseen: false, parent: [Object] },
     Item { item_id: 101, count: 26, unseen: false, parent: [Object] },
     Item { item_id: 102, count: 23, unseen: false, parent: [Object] },
     Item { item_id: 501, count: 2, unseen: false, parent: [Object] } ],
  eggs: 
   [ Pokemon {
       pokemon_id: 0,
       cp: 0,
       stamina: 0,
       stamina_max: 0,
       move_1: 0,
       move_2: 0,
       deployed_fort_id: 0,
       owner_name: '',
       is_egg: true,
       egg_km_walked_target: 2,
       egg_km_walked_start: 0,
       origin: 0,
       height_m: 0,
       weight_kg: 0,
       individual_attack: 0,
       individual_defense: 0,
       individual_stamina: 0,
       cp_multiplier: 0,
       pokeball: 0,
       captured_cell_id: [Object],
       battles_attacked: 0,
       battles_defended: 0,
       egg_incubator_id: '',
       creation_time_ms: [Object],
       num_upgrades: 0,
       additional_cp_multiplier: 0,
       favorite: 0,
       nickname: '',
       from_fort: 0,
       catchable: true,
       parent: [Object] },
     ] }

**Comment by jimmywarting** [comment]
Nice! lgtm

**Comment by gallexme** [comment]
checking if there is more useful data

**Comment by gallexme** [comment]
you can also only get the items which u got new between 2 requests by saving the old request time and asking for anything which is newer than that

aint got much more time to check for more data but it looks like those are filled too sometimes


    inventory_item_data: 
     { pokemon_data: null,
       item: null,
       pokedex_entry: null,
       player_stats: null,
       player_currency: null,
       player_camera: null,
       inventory_upgrades: null,
       applied_items: null,
       egg_incubators: null,
       pokemon_family: [Object] } },

**Comment by stoffern** [comment]
@gallexme status on this?

**Comment by gallexme** [comment]
Well it's working perfectly fine,  it's just missing some data from the Response,  but every item,  Pokémons,  eggs and candies are indluded, so you maybe can Merge it if u want

**Pull request merged**
