### PR TITLE
Fixes Pokemon Evolve/Release/Upgrade/Catchable/Console Spam

### PR DESCRIPTION
**Pull request by gallexme**
it wont mark all pokemons in the inventory as catcheable
also it stops spaming found Spearow. Direction: https://www.google.com/maps/dir/Current+Location/xxxxxxx
for pokemons inside the inventory

also fixed .id as its the unique id of the pokemon of player

### CODE REVIEW

**Comment by stoffern** [comment]
confirmed working?

**Comment by gallexme** [comment]
Definitely works with my inventory  Response object,  but I only testen release and evolve

**Comment by stoffern** [comment]
Can you fix the conflict?

**Comment by jimmywarting** [comment]
I have removed "found Direction"

**Comment by gallexme** [comment]
merged

**Comment by gallexme** [comment]
weird shit, may someone fix it pls? no time sorry

**Comment by stoffern** [comment]
Build fails. Syntax error. Will fix this later today.

**Comment by DaVarga** [comment]
Try PR #78

**Comment by stoffern** [comment]
@jimmywarting can you fix this merge for me? :)

**Comment by jimmywarting** [comment]
can do that in one hour

**Comment by gallexme** [comment]
@jimmywarting  almost
the function evolve is still called envolve

**Pull request closed without merging**
